### ISSUE TITLE
Sigma finiteness of `μ.map f`

### ISSUE THREAD

**Issue by LorenzoLuccioli** [RemyDegenne/testing-lower-bounds#56]
There are instances stating that if the measure `μ` is a probability measure, finite or S-finite, then the pushforward `μ.map f` is also a probability measure, finite or S-finite. Unfortunately the same is not true in general for sigma finiteness. 
However we have `MeasurableEquiv.sigmaFinite_map`, stating that this is true in the case of a measurable equivalence.
It may be possible to generalize this not to require a measurable equivalence, but only a measurable embedding. This would allow us to prove things like:  if `μ` is a sigma finite measure on a product space, then `μ.fst` and `μ.snd` are sigma finite.

**Comment by RemyDegenne** [comment]
I added the measurable embedding result to Mathlib.
